### ISSUE TITLE
PM Review: User Authentication

### ISSUE THREAD

**Issue by sunaynab** [sunaynab/focalize#30]

**Comment by sunaynab** [comment]
@louisscruz I think I've completed everything for user authentication. Do you mind reviewing my project and providing feedback?

**Comment by louisscruz** [comment]
It doesn't look like user sessions are persisting. If I log in and refresh, then the session goes away. Check the bootstrapping.

**Comment by louisscruz** [comment]
The error text should be a little larger (it's currently hard to read).

**Comment by louisscruz** [comment]
When I try to do the demo login, I get form errors, and the console says "Uncaught TypeError: Cannot read property 'preventDefault' of undefined"

**Comment by sunaynab** [comment]
​Completed the changes. Please let me know if you notice anything else.

Thanks!
Sunayna​
